export const categories = [
  "Repair",
  "Roofing",
  "Plumbing",
  "Carpentry",
  "Automotive",
  "Janitorial",
  "Electrical",
  "Landscaping",
  "Maintenance",
  "Construction",
];

export const foodItems = [
  {
    name: "Repair Machine",
    price: "13.40",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/tool-front-color.png"),
    type: "construction",
  },
  {
    name: "Paint My Room",
    price: "18.30",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/roll-brush-front-color.png"),
    type: "renovation",
  },
  {
    name: "Power Switch",
    price: "20.00",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/bulb-front-color.png"),
    type: "electrical",
  },
  {
    name: "Sofa Carpentry",
    price: "10.50",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/chess-front-color.png"),
    type: "carpentry",
  },
  {
    name: "Repair Machine",
    price: "13.40",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/tool-front-color.png"),
    type: "construction",
  },
  {
    name: "Paint My Room",
    price: "18.30",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/roll-brush-front-color.png"),
    type: "renovation",
  },
  {
    name: "Power Switch",
    price: "20.00",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/bulb-front-color.png"),
    type: "electrical",
  },
  {
    name: "Sofa Carpentry",
    price: "10.50",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/chess-front-color.png"),
    type: "carpentry",
  },
  {
    name: "Repair Machine",
    price: "13.40",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/tool-front-color.png"),
    type: "construction",
  },
  {
    name: "Paint My Room",
    price: "18.30",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/roll-brush-front-color.png"),
    type: "renovation",
  },
  {
    name: "Power Switch",
    price: "20.00",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/bulb-front-color.png"),
    type: "electrical",
  },
  {
    name: "Sofa Carpentry",
    price: "10.50",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/chess-front-color.png"),
    type: "carpentry",
  },
  {
    name: "Repair Machine",
    price: "13.40",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/tool-front-color.png"),
    type: "construction",
  },
  {
    name: "Paint My Room",
    price: "18.30",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/roll-brush-front-color.png"),
    type: "renovation",
  },
  {
    name: "Power Switch",
    price: "20.00",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/bulb-front-color.png"),
    type: "electrical",
  },
  {
    name: "Sofa Carpentry",
    price: "10.50",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/chess-front-color.png"),
    type: "carpentry",
  },
  {
    name: "Repair Machine",
    price: "13.40",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/tool-front-color.png"),
    type: "construction",
  },
  {
    name: "Paint My Room",
    price: "18.30",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/roll-brush-front-color.png"),
    type: "renovation",
  },
  {
    name: "Power Switch",
    price: "20.00",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/bulb-front-color.png"),
    type: "electrical",
  },
  {
    name: "Sofa Carpentry",
    price: "10.50",
    text: "lorem ipsum ....",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    image: require("../assets/images/chess-front-color.png"),
    type: "carpentry",
  },
];
